### ISSUE TITLE
SHA-3 vs Keccak-256 

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/nim-keccak-tiny#1]
The Ethereum Yellow Paper specifies `KECCAK-256`  "as per the winning entry to the SHA-3 contest", and not the `SHA-3 FIPS 202` standard.

If the tests are correct and outputting `a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a` for empty string, then this is SHA-3 and not suitable for Ethereum.

https://github.com/ethereum/yellowpaper  
https://ethereum.stackexchange.com/questions/550/which-cryptographic-hash-function-does-ethereum-use

```
keccak_256('');
// c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470

sha3_256('');
// a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a
```

**Comment by zah** [comment]
It turned out that there is only a minor difference between the original Keccak submission and the FIPS standard, namely a padding constant used within the algorithm.

I've kept both versions of the function and new tests were added here:
https://github.com/status-im/nim-keccak-tiny/commit/4bb4f588556f0bc1d04284a38a8beec91d53be43#diff-41b3b07f60012c4917716af7d9523f09
